spring:
  application:
    name: zuul-proxy

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

sidecar:
  port: 8000
  health-uri: http://localhost:8000/health.json